### ISSUE TITLE
Please add a license for this project

### ISSUE THREAD

**Issue by ccordoba12** [aroberge/mod_pydoc#4]
Hi @aroberge, we're working to improve how Pydoc documentation is shown in the [Spyder IDE](https://github.com/spyder-ide/spyder), and for that we'd like to use the code you developed as part of this project.

However, we can't do that unless you add a license for it, which should be compatible with our own MIT license (MIT or BSD licenses are fine).

Thanks!

**Comment by aroberge** [comment]
MIT license added.  I did not add a license originally as I was hoping this would be accepted as a PR for an issue recorded for CPython's standard library - an issue that is still open to this day ...

**Comment by ccordoba12** [comment]
Ok, thanks a lot for your quick response!
